/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppInstallWithClientRelationships {
    #[serde(rename = "app", skip_serializing_if = "Option::is_none")]
    pub app: Option<Box<crate::models::AppInstallWithClientRelationshipsApp>>,
}

impl AppInstallWithClientRelationships {
    pub fn new() -> AppInstallWithClientRelationships {
        AppInstallWithClientRelationships {
            app: None,
        }
    }
}


