/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppBot {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<serde_json::Value>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Box<crate::models::Links>>,
    #[serde(rename = "relationships")]
    pub relationships: Box<crate::models::AppBotRelationships>,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl AppBot {
    pub fn new(id: uuid::Uuid, relationships: crate::models::AppBotRelationships, r#type: String) -> AppBot {
        AppBot {
            attributes: None,
            id,
            links: None,
            relationships: Box::new(relationships),
            r#type,
        }
    }
}


