/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppInstallDataWithSecretAttributes {
    /// The oauth2 client id for the app.
    #[serde(rename = "client_id")]
    pub client_id: uuid::Uuid,
    /// The oauth2 client secret for the app. This is the only time this secret will be returned, store it securely and don’t lose it.
    #[serde(rename = "client_secret")]
    pub client_secret: String,
}

impl AppInstallDataWithSecretAttributes {
    pub fn new(client_id: uuid::Uuid, client_secret: String) -> AppInstallDataWithSecretAttributes {
        AppInstallDataWithSecretAttributes {
            client_id,
            client_secret,
        }
    }
}


