/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppBotRelationships {
    #[serde(rename = "app")]
    pub app: Box<crate::models::AppBotRelationshipsApp>,
}

impl AppBotRelationships {
    pub fn new(app: crate::models::AppBotRelationshipsApp) -> AppBotRelationships {
        AppBotRelationships {
            app: Box::new(app),
        }
    }
}


