/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppInstallWithClientAttributes {
    #[serde(rename = "client_id")]
    pub client_id: uuid::Uuid,
    #[serde(rename = "client_secret")]
    pub client_secret: String,
}

impl AppInstallWithClientAttributes {
    pub fn new(client_id: uuid::Uuid, client_secret: String) -> AppInstallWithClientAttributes {
        AppInstallWithClientAttributes {
            client_id,
            client_secret,
        }
    }
}


