/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppInstallWithClient {
    #[serde(rename = "attributes")]
    pub attributes: Box<crate::models::AppInstallWithClientAttributes>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Box<crate::models::Links>>,
    #[serde(rename = "relationships")]
    pub relationships: Box<crate::models::AppInstallWithClientRelationships>,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl AppInstallWithClient {
    pub fn new(attributes: crate::models::AppInstallWithClientAttributes, id: uuid::Uuid, relationships: crate::models::AppInstallWithClientRelationships, r#type: String) -> AppInstallWithClient {
        AppInstallWithClient {
            attributes: Box::new(attributes),
            id,
            links: None,
            relationships: Box::new(relationships),
            r#type,
        }
    }
}


