/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppPostRequestDataAttributes {
    /// The access token time to live for your app, in seconds. It only affects the newly generated access tokens, existing access token will  continue to have their previous time to live as expiration.
    #[serde(rename = "access_token_ttl_seconds", skip_serializing_if = "Option::is_none")]
    pub access_token_ttl_seconds: Option<f32>,
    #[serde(rename = "context")]
    pub context: crate::models::Context,
    /// New name of the app to display to users during authorization flow.
    #[serde(rename = "name")]
    pub name: String,
    /// List of allowed redirect URIs to call back after authentication.
    #[serde(rename = "redirect_uris")]
    pub redirect_uris: Vec<String>,
    /// The scopes this app is allowed to request during authorization.
    #[serde(rename = "scopes")]
    pub scopes: Vec<String>,
}

impl AppPostRequestDataAttributes {
    pub fn new(context: crate::models::Context, name: String, redirect_uris: Vec<String>, scopes: Vec<String>) -> AppPostRequestDataAttributes {
        AppPostRequestDataAttributes {
            access_token_ttl_seconds: None,
            context,
            name,
            redirect_uris,
            scopes,
        }
    }
}


