/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CollectionMeta {
    /// The sum of critical severity issues of the collection's projects
    #[serde(rename = "issues_critical_count")]
    pub issues_critical_count: f32,
    /// The sum of high severity issues of the collection's projects
    #[serde(rename = "issues_high_count")]
    pub issues_high_count: f32,
    /// The sum of low severity issues of the collection's projects
    #[serde(rename = "issues_low_count")]
    pub issues_low_count: f32,
    /// The sum of medium severity issues of the collection's projects
    #[serde(rename = "issues_medium_count")]
    pub issues_medium_count: f32,
    /// The amount of projects belonging to this collection
    #[serde(rename = "projects_count")]
    pub projects_count: f32,
}

impl CollectionMeta {
    pub fn new(issues_critical_count: f32, issues_high_count: f32, issues_low_count: f32, issues_medium_count: f32, projects_count: f32) -> CollectionMeta {
        CollectionMeta {
            issues_critical_count,
            issues_high_count,
            issues_low_count,
            issues_medium_count,
            projects_count,
        }
    }
}


