/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CollectionResponse {
    #[serde(rename = "attributes")]
    pub attributes: Box<crate::models::CollectionAttributes>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "meta")]
    pub meta: Box<crate::models::CollectionMeta>,
    #[serde(rename = "relationships")]
    pub relationships: Box<crate::models::CollectionRelationships>,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl CollectionResponse {
    pub fn new(attributes: crate::models::CollectionAttributes, id: uuid::Uuid, meta: crate::models::CollectionMeta, relationships: crate::models::CollectionRelationships, r#type: String) -> CollectionResponse {
        CollectionResponse {
            attributes: Box::new(attributes),
            id,
            meta: Box::new(meta),
            relationships: Box::new(relationships),
            r#type,
        }
    }
}


