/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CollectionRelationships {
    #[serde(rename = "created_by_user")]
    pub created_by_user: Box<crate::models::CollectionRelationshipsCreatedByUser>,
    #[serde(rename = "org")]
    pub org: Box<crate::models::CollectionRelationshipsOrg>,
}

impl CollectionRelationships {
    pub fn new(created_by_user: crate::models::CollectionRelationshipsCreatedByUser, org: crate::models::CollectionRelationshipsOrg) -> CollectionRelationships {
        CollectionRelationships {
            created_by_user: Box::new(created_by_user),
            org: Box::new(org),
        }
    }
}


