/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommonIssueModelAttributesCoordinatesInnerRemediesInner {
    /// A markdown-formatted optional description of this remedy.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<Box<crate::models::CommonIssueModelAttributesCoordinatesInnerRemediesInnerDetails>>,
    /// The type of the remedy. Always ‘indeterminate’.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl CommonIssueModelAttributesCoordinatesInnerRemediesInner {
    pub fn new() -> CommonIssueModelAttributesCoordinatesInnerRemediesInner {
        CommonIssueModelAttributesCoordinatesInnerRemediesInner {
            description: None,
            details: None,
            r#type: None,
        }
    }
}


