/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommonIssueModelAttributesCoordinatesInnerRemediesInnerDetails {
    /// A minimum version to upgrade to in order to remedy the issue.
    #[serde(rename = "upgrade_package", skip_serializing_if = "Option::is_none")]
    pub upgrade_package: Option<String>,
}

impl CommonIssueModelAttributesCoordinatesInnerRemediesInnerDetails {
    pub fn new() -> CommonIssueModelAttributesCoordinatesInnerRemediesInnerDetails {
        CommonIssueModelAttributesCoordinatesInnerRemediesInnerDetails {
            upgrade_package: None,
        }
    }
}


