/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommonIssueModelAttributesCoordinatesInner {
    #[serde(rename = "remedies", skip_serializing_if = "Option::is_none")]
    pub remedies: Option<Vec<crate::models::CommonIssueModelAttributesCoordinatesInnerRemediesInner>>,
    /// The affected versions of this vulnerability.
    #[serde(rename = "representation", skip_serializing_if = "Option::is_none")]
    pub representation: Option<Vec<String>>,
}

impl CommonIssueModelAttributesCoordinatesInner {
    pub fn new() -> CommonIssueModelAttributesCoordinatesInner {
        CommonIssueModelAttributesCoordinatesInner {
            remedies: None,
            representation: None,
        }
    }
}


