/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CoordinateRepresentationsInnerOneOf3 : A location within a file.



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CoordinateRepresentationsInnerOneOf3 {
    #[serde(rename = "sourceLocation")]
    pub source_location: Box<crate::models::SourceLocation>,
}

impl CoordinateRepresentationsInnerOneOf3 {
    /// A location within a file.
    pub fn new(source_location: crate::models::SourceLocation) -> CoordinateRepresentationsInnerOneOf3 {
        CoordinateRepresentationsInnerOneOf3 {
            source_location: Box::new(source_location),
        }
    }
}


