/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CoordinateRepresentationsInnerOneOf : An object that contains an opaque identifying string.



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CoordinateRepresentationsInnerOneOf {
    #[serde(rename = "resourcePath")]
    pub resource_path: String,
}

impl CoordinateRepresentationsInnerOneOf {
    /// An object that contains an opaque identifying string.
    pub fn new(resource_path: String) -> CoordinateRepresentationsInnerOneOf {
        CoordinateRepresentationsInnerOneOf {
            resource_path,
        }
    }
}


