/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CoordinateRepresentationsInnerOneOf1 : An object that contains a list of opaque identifying strings.



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CoordinateRepresentationsInnerOneOf1 {
    #[serde(rename = "dependency")]
    pub dependency: Box<crate::models::Dependency>,
}

impl CoordinateRepresentationsInnerOneOf1 {
    /// An object that contains a list of opaque identifying strings.
    pub fn new(dependency: crate::models::Dependency) -> CoordinateRepresentationsInnerOneOf1 {
        CoordinateRepresentationsInnerOneOf1 {
            dependency: Box::new(dependency),
        }
    }
}


