/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Coordinate {
    #[serde(rename = "is_fixable_manually", skip_serializing_if = "Option::is_none")]
    pub is_fixable_manually: Option<bool>,
    #[serde(rename = "is_fixable_snyk", skip_serializing_if = "Option::is_none")]
    pub is_fixable_snyk: Option<bool>,
    #[serde(rename = "is_fixable_upstream", skip_serializing_if = "Option::is_none")]
    pub is_fixable_upstream: Option<bool>,
    #[serde(rename = "is_patchable", skip_serializing_if = "Option::is_none")]
    pub is_patchable: Option<bool>,
    #[serde(rename = "is_pinnable", skip_serializing_if = "Option::is_none")]
    pub is_pinnable: Option<bool>,
    #[serde(rename = "is_upgradeable", skip_serializing_if = "Option::is_none")]
    pub is_upgradeable: Option<bool>,
    #[serde(rename = "reachability", skip_serializing_if = "Option::is_none")]
    pub reachability: Option<String>,
    #[serde(rename = "remedies", skip_serializing_if = "Option::is_none")]
    pub remedies: Option<Vec<crate::models::Remedy>>,
    /// A list of precise locations that surface an issue. A coordinate may have multiple representations. 
    #[serde(rename = "representations", skip_serializing_if = "Option::is_none")]
    pub representations: Option<Vec<crate::models::CoordinateRepresentationsInner>>,
}

impl Coordinate {
    pub fn new() -> Coordinate {
        Coordinate {
            is_fixable_manually: None,
            is_fixable_snyk: None,
            is_fixable_upstream: None,
            is_patchable: None,
            is_pinnable: None,
            is_upgradeable: None,
            reachability: None,
            remedies: None,
            representations: None,
        }
    }
}


