/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */

use super::CoordinateRepresentationsInnerOneOf;
use super::CoordinateRepresentationsInnerOneOf1;
use super::CoordinateRepresentationsInnerOneOf2;
use super::CoordinateRepresentationsInnerOneOf3;



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CoordinateRepresentationsInner {
    CoordinateRepresentationsInnerOneOf(Box<CoordinateRepresentationsInnerOneOf>),
    CoordinateRepresentationsInnerOneOf1(Box<CoordinateRepresentationsInnerOneOf1>),
    CoordinateRepresentationsInnerOneOf2(Box<CoordinateRepresentationsInnerOneOf2>),
    CoordinateRepresentationsInnerOneOf3(Box<CoordinateRepresentationsInnerOneOf3>),
}

impl Default for CoordinateRepresentationsInner {
    fn default() -> Self {
        Self::CoordinateRepresentationsInnerOneOf(Box::default())
    }
}


