/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateGroupAppInstallRequest {
    #[serde(rename = "data")]
    pub data: Box<crate::models::CreateGroupAppInstallRequestData>,
    #[serde(rename = "relationships")]
    pub relationships: Box<crate::models::CreateGroupAppInstallRequestRelationships>,
}

impl CreateGroupAppInstallRequest {
    pub fn new(data: crate::models::CreateGroupAppInstallRequestData, relationships: crate::models::CreateGroupAppInstallRequestRelationships) -> CreateGroupAppInstallRequest {
        CreateGroupAppInstallRequest {
            data: Box::new(data),
            relationships: Box::new(relationships),
        }
    }
}


