/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateCollection201ResponseData : collection resource object



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCollection201ResponseData {
    #[serde(rename = "attributes")]
    pub attributes: Box<crate::models::CollectionAttributes>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "relationships")]
    pub relationships: Box<crate::models::CollectionRelationships>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl CreateCollection201ResponseData {
    /// collection resource object
    pub fn new(attributes: crate::models::CollectionAttributes, id: uuid::Uuid, relationships: crate::models::CollectionRelationships) -> CreateCollection201ResponseData {
        CreateCollection201ResponseData {
            attributes: Box::new(attributes),
            id,
            relationships: Box::new(relationships),
            r#type: None,
        }
    }
}


