/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateGroupAppInstallRequestRelationships {
    #[serde(rename = "app")]
    pub app: Box<crate::models::CreateGroupAppInstallRequestRelationshipsApp>,
}

impl CreateGroupAppInstallRequestRelationships {
    pub fn new(app: crate::models::CreateGroupAppInstallRequestRelationshipsApp) -> CreateGroupAppInstallRequestRelationships {
        CreateGroupAppInstallRequestRelationships {
            app: Box::new(app),
        }
    }
}


