/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateGroupServiceAccount201Response {
    #[serde(rename = "data")]
    pub data: Box<crate::models::GetManyGroupServiceAccount200ResponseDataInner>,
    #[serde(rename = "jsonapi")]
    pub jsonapi: Box<crate::models::JsonApi>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Box<crate::models::Links>>,
}

impl CreateGroupServiceAccount201Response {
    pub fn new(data: crate::models::GetManyGroupServiceAccount200ResponseDataInner, jsonapi: crate::models::JsonApi) -> CreateGroupServiceAccount201Response {
        CreateGroupServiceAccount201Response {
            data: Box::new(data),
            jsonapi: Box::new(jsonapi),
            links: None,
        }
    }
}


