/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateOrgServiceAccountRequestData {
    #[serde(rename = "attributes")]
    pub attributes: Box<crate::models::CreateOrgServiceAccountRequestDataAttributes>,
    /// The Resource type.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
}

impl CreateOrgServiceAccountRequestData {
    pub fn new(attributes: crate::models::CreateOrgServiceAccountRequestDataAttributes) -> CreateOrgServiceAccountRequestData {
        CreateOrgServiceAccountRequestData {
            attributes: Box::new(attributes),
            r#type: None,
        }
    }
}

/// The Resource type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "service_account")]
    ServiceAccount,
}

impl Default for Type {
    fn default() -> Type {
        Self::ServiceAccount
    }
}

