/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCollectionRequestData {
    #[serde(rename = "attributes")]
    pub attributes: Box<crate::models::CreateCollectionRequestDataAttributes>,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl CreateCollectionRequestData {
    pub fn new(attributes: crate::models::CreateCollectionRequestDataAttributes, r#type: String) -> CreateCollectionRequestData {
        CreateCollectionRequestData {
            attributes: Box::new(attributes),
            r#type,
        }
    }
}


