/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCollectionRequestDataAttributes {
    /// User-defined name of the collection
    #[serde(rename = "name")]
    pub name: String,
}

impl CreateCollectionRequestDataAttributes {
    pub fn new(name: String) -> CreateCollectionRequestDataAttributes {
        CreateCollectionRequestDataAttributes {
            name,
        }
    }
}


