/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomBaseImageResponse {
    #[serde(rename = "data")]
    pub data: Box<crate::models::CustomBaseImageResource>,
    #[serde(rename = "jsonapi")]
    pub jsonapi: Box<crate::models::JsonApi>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Box<crate::models::SelfLink>>,
}

impl CustomBaseImageResponse {
    pub fn new(data: crate::models::CustomBaseImageResource, jsonapi: crate::models::JsonApi) -> CustomBaseImageResponse {
        CustomBaseImageResponse {
            data: Box::new(data),
            jsonapi: Box::new(jsonapi),
            links: None,
        }
    }
}


