/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomBaseImagePatchRequestData {
    #[serde(rename = "attributes")]
    pub attributes: Box<crate::models::CustomBaseImagePatchRequestDataAttributes>,
    /// The ID of the custom base image that should be updated. (Same one used in the URI)
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// This should always be \"custom_base_image\"
    #[serde(rename = "type")]
    pub r#type: String,
}

impl CustomBaseImagePatchRequestData {
    pub fn new(attributes: crate::models::CustomBaseImagePatchRequestDataAttributes, r#type: String) -> CustomBaseImagePatchRequestData {
        CustomBaseImagePatchRequestData {
            attributes: Box::new(attributes),
            id: None,
            r#type,
        }
    }
}


