/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomBaseImageAttributes {
    /// Whether this image should be recommended as a base image upgrade.  If set to true, this image could be shown as a base image upgrade to other projects. If set to false this image will never be recommended as an upgrade. 
    #[serde(rename = "include_in_recommendations")]
    pub include_in_recommendations: bool,
    /// The ID of the container project that the custom base image is based off of. The attributes of this custom base image are taken from the latest snapshot at the time of creation. This means that no changes should be made to the original project after the creation of the custom base image, as new snapshots created from any changes will NOT be picked up. 
    #[serde(rename = "project_id")]
    pub project_id: uuid::Uuid,
    #[serde(rename = "versioning_schema", skip_serializing_if = "Option::is_none")]
    pub versioning_schema: Option<Box<crate::models::VersioningSchema>>,
}

impl CustomBaseImageAttributes {
    pub fn new(include_in_recommendations: bool, project_id: uuid::Uuid) -> CustomBaseImageAttributes {
        CustomBaseImageAttributes {
            include_in_recommendations,
            project_id,
            versioning_schema: None,
        }
    }
}


