/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomBaseImagePatchRequest {
    #[serde(rename = "data")]
    pub data: Box<crate::models::CustomBaseImagePatchRequestData>,
}

impl CustomBaseImagePatchRequest {
    pub fn new(data: crate::models::CustomBaseImagePatchRequestData) -> CustomBaseImagePatchRequest {
        CustomBaseImagePatchRequest {
            data: Box::new(data),
        }
    }
}


