/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomBaseImagePostRequestData {
    #[serde(rename = "attributes")]
    pub attributes: Box<crate::models::CustomBaseImageAttributes>,
    /// This should always be \"custom_base_image\"
    #[serde(rename = "type")]
    pub r#type: String,
}

impl CustomBaseImagePostRequestData {
    pub fn new(attributes: crate::models::CustomBaseImageAttributes, r#type: String) -> CustomBaseImagePostRequestData {
        CustomBaseImagePostRequestData {
            attributes: Box::new(attributes),
            r#type,
        }
    }
}


