/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteProjectsFromCollectionRequestDataInner {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Type of the item id
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl DeleteProjectsFromCollectionRequestDataInner {
    pub fn new(id: uuid::Uuid, r#type: Type) -> DeleteProjectsFromCollectionRequestDataInner {
        DeleteProjectsFromCollectionRequestDataInner {
            id,
            r#type,
        }
    }
}

/// Type of the item id
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "project")]
    Project,
}

impl Default for Type {
    fn default() -> Type {
        Self::Project
    }
}

