/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EnvironmentTypeDef {
    #[serde(rename = "aws")]
    Aws,
    #[serde(rename = "azure")]
    Azure,
    #[serde(rename = "azure_ad")]
    AzureAd,
    #[serde(rename = "google")]
    Google,
    #[serde(rename = "scm")]
    Scm,
    #[serde(rename = "cli")]
    Cli,
    #[serde(rename = "tfc")]
    Tfc,

}

impl ToString for EnvironmentTypeDef {
    fn to_string(&self) -> String {
        match self {
            Self::Aws => String::from("aws"),
            Self::Azure => String::from("azure"),
            Self::AzureAd => String::from("azure_ad"),
            Self::Google => String::from("google"),
            Self::Scm => String::from("scm"),
            Self::Cli => String::from("cli"),
            Self::Tfc => String::from("tfc"),
        }
    }
}

impl Default for EnvironmentTypeDef {
    fn default() -> EnvironmentTypeDef {
        Self::Aws
    }
}




