/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilePosition {
    #[serde(rename = "column")]
    pub column: i32,
    #[serde(rename = "line")]
    pub line: i32,
}

impl FilePosition {
    pub fn new(column: i32, line: i32) -> FilePosition {
        FilePosition {
            column,
            line,
        }
    }
}


