/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSlackDefaultNotificationSettings200Response {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::SlackDefaultSettingsData>>,
    #[serde(rename = "jsonapi", skip_serializing_if = "Option::is_none")]
    pub jsonapi: Option<Box<crate::models::JsonApi>>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Box<crate::models::SelfLink>>,
}

impl GetSlackDefaultNotificationSettings200Response {
    pub fn new() -> GetSlackDefaultNotificationSettings200Response {
        GetSlackDefaultNotificationSettings200Response {
            data: None,
            jsonapi: None,
            links: None,
        }
    }
}


