/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCustomBaseImages400Response {
    #[serde(rename = "errors")]
    pub errors: Vec<crate::models::GetCustomBaseImages400ResponseErrorsInner>,
    #[serde(rename = "jsonapi")]
    pub jsonapi: Box<crate::models::GetCustomBaseImages400ResponseJsonapi>,
}

impl GetCustomBaseImages400Response {
    pub fn new(errors: Vec<crate::models::GetCustomBaseImages400ResponseErrorsInner>, jsonapi: crate::models::GetCustomBaseImages400ResponseJsonapi) -> GetCustomBaseImages400Response {
        GetCustomBaseImages400Response {
            errors,
            jsonapi: Box::new(jsonapi),
        }
    }
}


