/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCustomBaseImages400ResponseErrorsInner {
    /// An application-specific error code, expressed as a string value.
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// A human-readable explanation specific to this occurrence of the problem.
    #[serde(rename = "detail")]
    pub detail: String,
    /// A unique identifier for this particular occurrence of the problem.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Box<crate::models::GetCustomBaseImages400ResponseErrorsInnerLinks>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<Box<crate::models::GetCustomBaseImages400ResponseErrorsInnerSource>>,
    /// The HTTP status code applicable to this problem, expressed as a string value.
    #[serde(rename = "status")]
    pub status: String,
    /// A short, human-readable summary of the problem that SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
}

impl GetCustomBaseImages400ResponseErrorsInner {
    pub fn new(detail: String, status: String) -> GetCustomBaseImages400ResponseErrorsInner {
        GetCustomBaseImages400ResponseErrorsInner {
            code: None,
            detail,
            id: None,
            links: None,
            meta: None,
            source: None,
            status,
            title: None,
        }
    }
}


