/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetUserAppSessions200Response {
    #[serde(rename = "data")]
    pub data: Vec<crate::models::SessionData>,
    #[serde(rename = "jsonapi")]
    pub jsonapi: Box<crate::models::JsonApi>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Box<crate::models::PaginatedLinks>>,
}

impl GetUserAppSessions200Response {
    pub fn new(data: Vec<crate::models::SessionData>, jsonapi: crate::models::JsonApi) -> GetUserAppSessions200Response {
        GetUserAppSessions200Response {
            data,
            jsonapi: Box::new(jsonapi),
            links: None,
        }
    }
}


