/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */

use super::GetCustomBaseImages400ResponseErrorsInnerLinksAboutOneOf;



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetCustomBaseImages400ResponseErrorsInnerLinksAbout {
    GetCustomBaseImages400ResponseErrorsInnerLinksAboutOneOf(Box<GetCustomBaseImages400ResponseErrorsInnerLinksAboutOneOf>),
    String(Box<String>),
}

impl Default for GetCustomBaseImages400ResponseErrorsInnerLinksAbout {
    fn default() -> Self {
        Self::GetCustomBaseImages400ResponseErrorsInnerLinksAboutOneOf(Box::default())
    }
}


