/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetApps200Response {
    #[serde(rename = "data")]
    pub data: Vec<crate::models::AppData>,
    #[serde(rename = "jsonapi")]
    pub jsonapi: Box<crate::models::JsonApi>,
    #[serde(rename = "links")]
    pub links: Box<crate::models::PaginatedLinks>,
}

impl GetApps200Response {
    pub fn new(data: Vec<crate::models::AppData>, jsonapi: crate::models::JsonApi, links: crate::models::PaginatedLinks) -> GetApps200Response {
        GetApps200Response {
            data,
            jsonapi: Box::new(jsonapi),
            links: Box::new(links),
        }
    }
}


