/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetManyGroupServiceAccount200Response {
    #[serde(rename = "data")]
    pub data: Vec<crate::models::GetManyGroupServiceAccount200ResponseDataInner>,
    #[serde(rename = "jsonapi")]
    pub jsonapi: Box<crate::models::JsonApi>,
    #[serde(rename = "links")]
    pub links: Box<crate::models::Links>,
}

impl GetManyGroupServiceAccount200Response {
    pub fn new(data: Vec<crate::models::GetManyGroupServiceAccount200ResponseDataInner>, jsonapi: crate::models::JsonApi, links: crate::models::Links) -> GetManyGroupServiceAccount200Response {
        GetManyGroupServiceAccount200Response {
            data,
            jsonapi: Box::new(jsonapi),
            links: Box::new(links),
        }
    }
}


