/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GroupIacSettingsResponseAttributesCustomRules : The Infrastructure as Code custom rules settings for a group.



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupIacSettingsResponseAttributesCustomRules {
    /// Whether the custom rules feature is enabled or not.
    #[serde(rename = "is_enabled", skip_serializing_if = "Option::is_none")]
    pub is_enabled: Option<bool>,
    /// The tag for an OCI artifact inside an OCI registry.
    #[serde(rename = "oci_registry_tag", skip_serializing_if = "Option::is_none")]
    pub oci_registry_tag: Option<String>,
    /// The URL to an OCI registry.
    #[serde(rename = "oci_registry_url", skip_serializing_if = "Option::is_none")]
    pub oci_registry_url: Option<String>,
}

impl GroupIacSettingsResponseAttributesCustomRules {
    /// The Infrastructure as Code custom rules settings for a group.
    pub fn new() -> GroupIacSettingsResponseAttributesCustomRules {
        GroupIacSettingsResponseAttributesCustomRules {
            is_enabled: None,
            oci_registry_tag: None,
            oci_registry_url: None,
        }
    }
}


