/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupIacSettingsResponseAttributes {
    #[serde(rename = "custom_rules", skip_serializing_if = "Option::is_none")]
    pub custom_rules: Option<Box<crate::models::GroupIacSettingsResponseAttributesCustomRules>>,
    /// The last time the settings were updated.
    #[serde(rename = "updated", skip_serializing_if = "Option::is_none")]
    pub updated: Option<String>,
}

impl GroupIacSettingsResponseAttributes {
    pub fn new() -> GroupIacSettingsResponseAttributes {
        GroupIacSettingsResponseAttributes {
            custom_rules: None,
            updated: None,
        }
    }
}


