/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HelloWorldAttributesRequestSubject {
    #[serde(rename = "clientId", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<uuid::Uuid>,
    #[serde(rename = "publicId")]
    pub public_id: uuid::Uuid,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl HelloWorldAttributesRequestSubject {
    pub fn new(public_id: uuid::Uuid, r#type: String) -> HelloWorldAttributesRequestSubject {
        HelloWorldAttributesRequestSubject {
            client_id: None,
            public_id,
            r#type,
        }
    }
}


