/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueRelationshipsOrganization {
    #[serde(rename = "data")]
    pub data: Box<crate::models::IssueRelationshipsOrganizationData>,
}

impl IssueRelationshipsOrganization {
    pub fn new(data: crate::models::IssueRelationshipsOrganizationData) -> IssueRelationshipsOrganization {
        IssueRelationshipsOrganization {
            data: Box::new(data),
        }
    }
}


