/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IssueRelationshipsTestExecutions : The \"test execution\" that identified this Issues. This ID represents a grouping of issues, that were identified by some analysis run, to produce Issues. 



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueRelationshipsTestExecutions {
    /// List of metadata associated with the test executions that identified this issue
    #[serde(rename = "data")]
    pub data: Vec<crate::models::IssueRelationshipsTestExecutionsDataInner>,
}

impl IssueRelationshipsTestExecutions {
    /// The \"test execution\" that identified this Issues. This ID represents a grouping of issues, that were identified by some analysis run, to produce Issues. 
    pub fn new(data: Vec<crate::models::IssueRelationshipsTestExecutionsDataInner>) -> IssueRelationshipsTestExecutions {
        IssueRelationshipsTestExecutions {
            data,
        }
    }
}


