/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueRelationshipsOrganizationData {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "type")]
    pub r#type: crate::models::OrganizationType,
}

impl IssueRelationshipsOrganizationData {
    pub fn new(id: uuid::Uuid, r#type: crate::models::OrganizationType) -> IssueRelationshipsOrganizationData {
        IssueRelationshipsOrganizationData {
            id,
            r#type,
        }
    }
}


