/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IssueRelationships : issue relationships



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueRelationships {
    #[serde(rename = "ignore", skip_serializing_if = "Option::is_none")]
    pub ignore: Option<Box<crate::models::IssueRelationshipsIgnore>>,
    #[serde(rename = "organization")]
    pub organization: Box<crate::models::IssueRelationshipsOrganization>,
    #[serde(rename = "scan_item")]
    pub scan_item: Box<crate::models::IssueRelationshipsScanItem>,
    #[serde(rename = "test_executions", skip_serializing_if = "Option::is_none")]
    pub test_executions: Option<Box<crate::models::IssueRelationshipsTestExecutions>>,
}

impl IssueRelationships {
    /// issue relationships
    pub fn new(organization: crate::models::IssueRelationshipsOrganization, scan_item: crate::models::IssueRelationshipsScanItem) -> IssueRelationships {
        IssueRelationships {
            ignore: None,
            organization: Box::new(organization),
            scan_item: Box::new(scan_item),
            test_executions: None,
        }
    }
}


