/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssuesMeta {
    #[serde(rename = "package", skip_serializing_if = "Option::is_none")]
    pub package: Option<Box<crate::models::PackageMeta>>,
}

impl IssuesMeta {
    pub fn new() -> IssuesMeta {
        IssuesMeta {
            package: None,
        }
    }
}


