/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LatestIssueCounts {
    #[serde(rename = "critical", skip_serializing_if = "Option::is_none")]
    pub critical: Option<f32>,
    #[serde(rename = "high", skip_serializing_if = "Option::is_none")]
    pub high: Option<f32>,
    #[serde(rename = "low", skip_serializing_if = "Option::is_none")]
    pub low: Option<f32>,
    #[serde(rename = "medium", skip_serializing_if = "Option::is_none")]
    pub medium: Option<f32>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl LatestIssueCounts {
    pub fn new() -> LatestIssueCounts {
        LatestIssueCounts {
            critical: None,
            high: None,
            low: None,
            medium: None,
            updated_at: None,
        }
    }
}


