/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListChannels200Response {
    #[serde(rename = "data")]
    pub data: Vec<crate::models::SlackChannel>,
    #[serde(rename = "jsonapi")]
    pub jsonapi: Box<crate::models::JsonApi>,
    #[serde(rename = "links")]
    pub links: Box<crate::models::PaginatedLinks>,
}

impl ListChannels200Response {
    pub fn new(data: Vec<crate::models::SlackChannel>, jsonapi: crate::models::JsonApi, links: crate::models::PaginatedLinks) -> ListChannels200Response {
        ListChannels200Response {
            data,
            jsonapi: Box::new(jsonapi),
            links: Box::new(links),
        }
    }
}


