/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListGroupAuditLogs200Response {
    #[serde(rename = "data")]
    pub data: Box<crate::models::AuditLogSearch>,
    #[serde(rename = "jsonapi")]
    pub jsonapi: Box<crate::models::JsonApi>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Box<crate::models::Links>>,
}

impl ListGroupAuditLogs200Response {
    pub fn new(data: crate::models::AuditLogSearch, jsonapi: crate::models::JsonApi) -> ListGroupAuditLogs200Response {
        ListGroupAuditLogs200Response {
            data: Box::new(data),
            jsonapi: Box::new(jsonapi),
            links: None,
        }
    }
}


