/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListOrgProjects200Response {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<crate::models::ListOrgProjects200ResponseDataInner>>,
    #[serde(rename = "jsonapi")]
    pub jsonapi: Box<crate::models::JsonApi>,
    #[serde(rename = "links")]
    pub links: Box<crate::models::Links>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::ListOrgProjects200ResponseMeta>>,
}

impl ListOrgProjects200Response {
    pub fn new(jsonapi: crate::models::JsonApi, links: crate::models::Links) -> ListOrgProjects200Response {
        ListOrgProjects200Response {
            data: None,
            jsonapi: Box::new(jsonapi),
            links: Box::new(links),
            meta: None,
        }
    }
}


