/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NugetBuildArgs {
    #[serde(rename = "target_framework")]
    pub target_framework: String,
}

impl NugetBuildArgs {
    pub fn new(target_framework: String) -> NugetBuildArgs {
        NugetBuildArgs {
            target_framework,
        }
    }
}


