/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrgInvitation {
    #[serde(rename = "attributes")]
    pub attributes: Box<crate::models::OrgInvitationAttributes>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<Box<crate::models::OrgInvitationRelationships>>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl OrgInvitation {
    pub fn new(attributes: crate::models::OrgInvitationAttributes, id: uuid::Uuid, r#type: Type) -> OrgInvitation {
        OrgInvitation {
            attributes: Box::new(attributes),
            id,
            relationships: None,
            r#type,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "org_invitation")]
    OrgInvitation,
}

impl Default for Type {
    fn default() -> Type {
        Self::OrgInvitation
    }
}

