/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrgRelationships {
    #[serde(rename = "member_role", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub member_role: Option<Option<Box<crate::models::MemberRoleRelationship>>>,
}

impl OrgRelationships {
    pub fn new() -> OrgRelationships {
        OrgRelationships {
            member_role: None,
        }
    }
}


