/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrgInvitationPostAttributes {
    /// The email address of the invitee.
    #[serde(rename = "email")]
    pub email: String,
    /// The role public ID that will be granted to to invitee on acceptance.
    #[serde(rename = "role", deserialize_with = "Option::deserialize")]
    pub role: Option<serde_json::Value>,
}

impl OrgInvitationPostAttributes {
    pub fn new(email: String, role: Option<serde_json::Value>) -> OrgInvitationPostAttributes {
        OrgInvitationPostAttributes {
            email,
            role,
        }
    }
}


