/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrgWithRelationships {
    #[serde(rename = "attributes")]
    pub attributes: Box<crate::models::OrgAttributes>,
    /// The Snyk ID of the organization.
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<Box<crate::models::OrgRelationships>>,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl OrgWithRelationships {
    pub fn new(attributes: crate::models::OrgAttributes, id: uuid::Uuid, r#type: String) -> OrgWithRelationships {
        OrgWithRelationships {
            attributes: Box::new(attributes),
            id,
            relationships: None,
            r#type,
        }
    }
}


