/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchProjectRequestDataRelationshipsOwnerData {
    /// The public ID of the user that owns the project
    #[serde(rename = "id", deserialize_with = "Option::deserialize")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl PatchProjectRequestDataRelationshipsOwnerData {
    pub fn new(id: Option<uuid::Uuid>, r#type: Type) -> PatchProjectRequestDataRelationshipsOwnerData {
        PatchProjectRequestDataRelationshipsOwnerData {
            id,
            r#type,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "user")]
    User,
}

impl Default for Type {
    fn default() -> Type {
        Self::User
    }
}

