/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProblemTypeDef {
    #[serde(rename = "rule")]
    Rule,
    #[serde(rename = "vulnerability")]
    Vulnerability,

}

impl ToString for ProblemTypeDef {
    fn to_string(&self) -> String {
        match self {
            Self::Rule => String::from("rule"),
            Self::Vulnerability => String::from("vulnerability"),
        }
    }
}

impl Default for ProblemTypeDef {
    fn default() -> ProblemTypeDef {
        Self::Rule
    }
}




