/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Problem {
    /// When this problem was disclosed to the public.
    #[serde(rename = "disclosed_at", skip_serializing_if = "Option::is_none")]
    pub disclosed_at: Option<String>,
    /// When this problem was first discovered.
    #[serde(rename = "discovered_at", skip_serializing_if = "Option::is_none")]
    pub discovered_at: Option<String>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "source")]
    pub source: String,
    #[serde(rename = "type")]
    pub r#type: crate::models::ProblemTypeDef,
    /// When this problem was last updated.
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    /// An optional URL for this problem.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl Problem {
    pub fn new(id: String, source: String, r#type: crate::models::ProblemTypeDef) -> Problem {
        Problem {
            disclosed_at: None,
            discovered_at: None,
            id,
            source,
            r#type,
            updated_at: None,
            url: None,
        }
    }
}


