/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectSettingsPatchRequestDataAttributes {
    /// Current status of the project settings.
    #[serde(rename = "is_active", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    #[serde(rename = "severity_threshold", skip_serializing_if = "Option::is_none")]
    pub severity_threshold: Option<crate::models::SeverityThreshold>,
    #[serde(rename = "target_channel_id", skip_serializing_if = "Option::is_none")]
    pub target_channel_id: Option<String>,
}

impl ProjectSettingsPatchRequestDataAttributes {
    pub fn new() -> ProjectSettingsPatchRequestDataAttributes {
        ProjectSettingsPatchRequestDataAttributes {
            is_active: None,
            severity_threshold: None,
            target_channel_id: None,
        }
    }
}


