/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectOfCollection {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "meta")]
    pub meta: Box<crate::models::ProjectMeta>,
    #[serde(rename = "relationships")]
    pub relationships: Box<crate::models::ProjectOfCollectionRelationships>,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl ProjectOfCollection {
    pub fn new(id: uuid::Uuid, meta: crate::models::ProjectMeta, relationships: crate::models::ProjectOfCollectionRelationships, r#type: String) -> ProjectOfCollection {
        ProjectOfCollection {
            id,
            meta: Box::new(meta),
            relationships: Box::new(relationships),
            r#type,
        }
    }
}


