/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */

use super::ContainerBuildArgs;
use super::NugetBuildArgs;
use super::YarnBuildArgs;



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ProjectAttributesBuildArgs {
    ContainerBuildArgs(Box<ContainerBuildArgs>),
    NugetBuildArgs(Box<NugetBuildArgs>),
    YarnBuildArgs(Box<YarnBuildArgs>),
}

impl Default for ProjectAttributesBuildArgs {
    fn default() -> Self {
        Self::ContainerBuildArgs(Box::default())
    }
}


