/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectOfCollectionRelationships {
    #[serde(rename = "target")]
    pub target: Box<crate::models::ProjectOfCollectionRelationshipsTarget>,
}

impl ProjectOfCollectionRelationships {
    pub fn new(target: crate::models::ProjectOfCollectionRelationshipsTarget) -> ProjectOfCollectionRelationships {
        ProjectOfCollectionRelationships {
            target: Box::new(target),
        }
    }
}


