/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectRelationshipsTargetDataMeta {
    /// A collection of properties regarding integration data
    #[serde(rename = "integration_data", skip_serializing_if = "Option::is_none")]
    pub integration_data: Option<serde_json::Value>,
}

impl ProjectRelationshipsTargetDataMeta {
    pub fn new() -> ProjectRelationshipsTargetDataMeta {
        ProjectRelationshipsTargetDataMeta {
            integration_data: None,
        }
    }
}


