/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectRelationships {
    #[serde(rename = "importer", skip_serializing_if = "Option::is_none")]
    pub importer: Option<Box<crate::models::Relationship>>,
    #[serde(rename = "organization")]
    pub organization: Box<crate::models::Relationship>,
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<Box<crate::models::Relationship>>,
    #[serde(rename = "target")]
    pub target: Box<crate::models::ProjectRelationshipsTarget>,
}

impl ProjectRelationships {
    pub fn new(organization: crate::models::Relationship, target: crate::models::ProjectRelationshipsTarget) -> ProjectRelationships {
        ProjectRelationships {
            importer: None,
            organization: Box::new(organization),
            owner: None,
            target: Box::new(target),
        }
    }
}


