/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */

use super::Relationship;



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ProjectRelationshipsTarget {
    ProjectRelationshipsTarget(Box<ProjectRelationshipsTarget>),
    Relationship(Box<Relationship>),
}

impl Default for ProjectRelationshipsTarget {
    fn default() -> Self {
        Self::ProjectRelationshipsTarget(Box::default())
    }
}


