/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectMeta {
    /// The time the project was imported
    #[serde(rename = "imported")]
    pub imported: String,
    /// The sum of critical severity issues of the project
    #[serde(rename = "issues_critical_count")]
    pub issues_critical_count: f32,
    /// The sum of high severity issues of the project
    #[serde(rename = "issues_high_count")]
    pub issues_high_count: f32,
    /// The sum of low severity issues of the project
    #[serde(rename = "issues_low_count")]
    pub issues_low_count: f32,
    /// The sum of medium severity issues of the project
    #[serde(rename = "issues_medium_count")]
    pub issues_medium_count: f32,
    /// The time the project was last tested
    #[serde(rename = "last_tested_at")]
    pub last_tested_at: String,
}

impl ProjectMeta {
    pub fn new(imported: String, issues_critical_count: f32, issues_high_count: f32, issues_low_count: f32, issues_medium_count: f32, last_tested_at: String) -> ProjectMeta {
        ProjectMeta {
            imported,
            issues_critical_count,
            issues_high_count,
            issues_low_count,
            issues_medium_count,
            last_tested_at,
        }
    }
}


