/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectSettingsDataAttributes {
    /// Current status of the project settings.
    #[serde(rename = "is_active")]
    pub is_active: bool,
    #[serde(rename = "severity_threshold")]
    pub severity_threshold: crate::models::SeverityThreshold,
    #[serde(rename = "target_channel_id")]
    pub target_channel_id: String,
    #[serde(rename = "target_channel_name")]
    pub target_channel_name: String,
    /// The target file name for the project.
    #[serde(rename = "target_project_name")]
    pub target_project_name: String,
}

impl ProjectSettingsDataAttributes {
    pub fn new(is_active: bool, severity_threshold: crate::models::SeverityThreshold, target_channel_id: String, target_channel_name: String, target_project_name: String) -> ProjectSettingsDataAttributes {
        ProjectSettingsDataAttributes {
            is_active,
            severity_threshold,
            target_channel_id,
            target_channel_name,
            target_project_name,
        }
    }
}


