/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicFacingRiskFactor {
    #[serde(rename = "included_in_score", skip_serializing_if = "Option::is_none")]
    pub included_in_score: Option<bool>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Box<crate::models::RiskFactorLinks>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "value")]
    pub value: bool,
}

impl PublicFacingRiskFactor {
    pub fn new(name: String, updated_at: String, value: bool) -> PublicFacingRiskFactor {
        PublicFacingRiskFactor {
            included_in_score: None,
            links: None,
            name,
            updated_at,
            value,
        }
    }
}


