/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicApp {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::PublicAppAttributes>>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Box<crate::models::Links>>,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl PublicApp {
    pub fn new(id: uuid::Uuid, r#type: String) -> PublicApp {
        PublicApp {
            attributes: None,
            id,
            links: None,
            r#type,
        }
    }
}


