/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicAppDataAttributes {
    #[serde(rename = "client_id")]
    pub client_id: uuid::Uuid,
    /// Allow installing the app to a org/group or to a user, default tenant.
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<Context>,
    /// New name of the app to display to users during authorization flow.
    #[serde(rename = "name")]
    pub name: String,
    /// The scopes this app is allowed to request during authorization.
    #[serde(rename = "scopes", skip_serializing_if = "Option::is_none")]
    pub scopes: Option<Vec<String>>,
}

impl PublicAppDataAttributes {
    pub fn new(client_id: uuid::Uuid, name: String) -> PublicAppDataAttributes {
        PublicAppDataAttributes {
            client_id,
            context: None,
            name,
            scopes: None,
        }
    }
}

/// Allow installing the app to a org/group or to a user, default tenant.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Context {
    #[serde(rename = "tenant")]
    Tenant,
    #[serde(rename = "user")]
    User,
}

impl Default for Context {
    fn default() -> Context {
        Self::Tenant
    }
}

