/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Relationship {
    #[serde(rename = "data")]
    pub data: Box<crate::models::RelationshipData>,
    #[serde(rename = "links")]
    pub links: Box<crate::models::RelatedLink>,
    /// Free-form object that may contain non-standard information.
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl Relationship {
    pub fn new(data: crate::models::RelationshipData, links: crate::models::RelatedLink) -> Relationship {
        Relationship {
            data: Box::new(data),
            links: Box::new(links),
            meta: None,
        }
    }
}


