/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Remedy {
    /// An optional identifier for correlating remedies between coordinates or across issues. They are scoped to a single Project and test run. Remedies with the same correlation_id must have the same contents. 
    #[serde(rename = "correlation_id", skip_serializing_if = "Option::is_none")]
    pub correlation_id: Option<String>,
    /// A markdown-formatted optional description of this remedy. Links are not permitted.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::RemedyMetadata>>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl Remedy {
    pub fn new(r#type: Type) -> Remedy {
        Remedy {
            correlation_id: None,
            description: None,
            meta: None,
            r#type,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "indeterminate")]
    Indeterminate,
    #[serde(rename = "manual")]
    Manual,
    #[serde(rename = "automated")]
    Automated,
    #[serde(rename = "rule_result_message")]
    RuleResultMessage,
    #[serde(rename = "terraform")]
    Terraform,
    #[serde(rename = "cloudformation")]
    Cloudformation,
    #[serde(rename = "cli")]
    Cli,
    #[serde(rename = "kubernetes")]
    Kubernetes,
    #[serde(rename = "arm")]
    Arm,
}

impl Default for Type {
    fn default() -> Type {
        Self::Indeterminate
    }
}

