/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Resolution : An optional field recording when and via what means an issue was resolved, if it was resolved. Resolved issues are retained for XX days. 



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Resolution {
    /// Optional details about the resolution. Used by Snyk Cloud so far.
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
    /// The time when this issue was resolved.
    #[serde(rename = "resolved_at")]
    pub resolved_at: String,
    #[serde(rename = "type")]
    pub r#type: crate::models::ResolutionTypeDef,
}

impl Resolution {
    /// An optional field recording when and via what means an issue was resolved, if it was resolved. Resolved issues are retained for XX days. 
    pub fn new(resolved_at: String, r#type: crate::models::ResolutionTypeDef) -> Resolution {
        Resolution {
            details: None,
            resolved_at,
            r#type,
        }
    }
}


