/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ResolutionTypeDef {
    #[serde(rename = "disappeared")]
    Disappeared,
    #[serde(rename = "fixed")]
    Fixed,

}

impl ToString for ResolutionTypeDef {
    fn to_string(&self) -> String {
        match self {
            Self::Disappeared => String::from("disappeared"),
            Self::Fixed => String::from("fixed"),
        }
    }
}

impl Default for ResolutionTypeDef {
    fn default() -> ResolutionTypeDef {
        Self::Disappeared
    }
}




