/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Risk : Risk prioritization information for an issue



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Risk {
    /// Risk factors identified for an issue
    #[serde(rename = "factors")]
    pub factors: Vec<crate::models::RiskFactor>,
    #[serde(rename = "score", skip_serializing_if = "Option::is_none")]
    pub score: Option<Box<crate::models::RiskScore>>,
}

impl Risk {
    /// Risk prioritization information for an issue
    pub fn new(factors: Vec<crate::models::RiskFactor>) -> Risk {
        Risk {
            factors,
            score: None,
        }
    }
}


