/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RiskFactorLinks {
    #[serde(rename = "evidence", skip_serializing_if = "Option::is_none")]
    pub evidence: Option<Box<crate::models::LinkProperty>>,
}

impl RiskFactorLinks {
    pub fn new() -> RiskFactorLinks {
        RiskFactorLinks {
            evidence: None,
        }
    }
}


