/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SbomResponse {
    #[serde(rename = "data")]
    pub data: Box<crate::models::SbomResource>,
    #[serde(rename = "jsonapi")]
    pub jsonapi: Box<crate::models::JsonApi>,
}

impl SbomResponse {
    pub fn new(data: crate::models::SbomResource, jsonapi: crate::models::JsonApi) -> SbomResponse {
        SbomResponse {
            data: Box::new(data),
            jsonapi: Box::new(jsonapi),
        }
    }
}


