/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionAttributes {
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl SessionAttributes {
    pub fn new(created_at: String) -> SessionAttributes {
        SessionAttributes {
            created_at,
        }
    }
}


