/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SettingsRequestData {
    #[serde(rename = "attributes")]
    pub attributes: Box<crate::models::SettingsAttributes>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl SettingsRequestData {
    pub fn new(attributes: crate::models::SettingsAttributes, r#type: Type) -> SettingsRequestData {
        SettingsRequestData {
            attributes: Box::new(attributes),
            r#type,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "slack")]
    Slack,
}

impl Default for Type {
    fn default() -> Type {
        Self::Slack
    }
}

