/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SeverityThreshold : Minimum Snyk issue severity to send a notification for, messages will not be sent for any issue below this value

/// Minimum Snyk issue severity to send a notification for, messages will not be sent for any issue below this value
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SeverityThreshold {
    #[serde(rename = "low")]
    Low,
    #[serde(rename = "medium")]
    Medium,
    #[serde(rename = "high")]
    High,
    #[serde(rename = "critical")]
    Critical,

}

impl ToString for SeverityThreshold {
    fn to_string(&self) -> String {
        match self {
            Self::Low => String::from("low"),
            Self::Medium => String::from("medium"),
            Self::High => String::from("high"),
            Self::Critical => String::from("critical"),
        }
    }
}

impl Default for SeverityThreshold {
    fn default() -> SeverityThreshold {
        Self::Low
    }
}




