/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Slots {
    /// The time at which this vulnerability was disclosed.
    #[serde(rename = "disclosure_time", skip_serializing_if = "Option::is_none")]
    pub disclosure_time: Option<String>,
    /// The exploit maturity. Value of ‘No Data’, ‘Not Defined’, ‘Unproven’, ‘Proof of Concept’, ‘Functional’ or ‘High’.
    #[serde(rename = "exploit", skip_serializing_if = "Option::is_none")]
    pub exploit: Option<String>,
    /// The time at which this vulnerability was published.
    #[serde(rename = "publication_time", skip_serializing_if = "Option::is_none")]
    pub publication_time: Option<String>,
    #[serde(rename = "references", skip_serializing_if = "Option::is_none")]
    pub references: Option<Vec<crate::models::SlotsReferencesInner>>,
}

impl Slots {
    pub fn new() -> Slots {
        Slots {
            disclosure_time: None,
            exploit: None,
            publication_time: None,
            references: None,
        }
    }
}


