/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SlotsReferencesInner {
    /// Descriptor for an external reference to the issue
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// URL for an external reference to the issue
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl SlotsReferencesInner {
    pub fn new() -> SlotsReferencesInner {
        SlotsReferencesInner {
            title: None,
            url: None,
        }
    }
}


