/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TypeDef : The type of an issue.

/// The type of an issue.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TypeDef {
    #[serde(rename = "package_vulnerability")]
    PackageVulnerability,
    #[serde(rename = "license")]
    License,
    #[serde(rename = "cloud")]
    Cloud,
    #[serde(rename = "code")]
    Code,
    #[serde(rename = "custom")]
    Custom,
    #[serde(rename = "config")]
    Config,

}

impl ToString for TypeDef {
    fn to_string(&self) -> String {
        match self {
            Self::PackageVulnerability => String::from("package_vulnerability"),
            Self::License => String::from("license"),
            Self::Cloud => String::from("cloud"),
            Self::Code => String::from("code"),
            Self::Custom => String::from("custom"),
            Self::Config => String::from("config"),
        }
    }
}

impl Default for TypeDef {
    fn default() -> TypeDef {
        Self::PackageVulnerability
    }
}




