/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateOrgProject200ResponseData {
    #[serde(rename = "attributes")]
    pub attributes: Box<crate::models::ProjectAttributes>,
    /// The Resource ID.
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Box<crate::models::Links>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::UpdateOrgProject200ResponseDataMeta>>,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<Box<crate::models::ProjectRelationships>>,
    /// The Resource type.
    #[serde(rename = "type")]
    pub r#type: String,
}

impl UpdateOrgProject200ResponseData {
    pub fn new(attributes: crate::models::ProjectAttributes, id: uuid::Uuid, r#type: String) -> UpdateOrgProject200ResponseData {
        UpdateOrgProject200ResponseData {
            attributes: Box::new(attributes),
            id,
            links: None,
            meta: None,
            relationships: None,
            r#type,
        }
    }
}


