/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateOrgSastSettingsRequestDataAttributes {
    /// The value of the updated settings for sastEnabled setting
    #[serde(rename = "sast_enabled")]
    pub sast_enabled: bool,
}

impl UpdateOrgSastSettingsRequestDataAttributes {
    pub fn new(sast_enabled: bool) -> UpdateOrgSastSettingsRequestDataAttributes {
        UpdateOrgSastSettingsRequestDataAttributes {
            sast_enabled,
        }
    }
}


