/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateOrgServiceAccountRequestDataAttributes {
    /// A human-friendly name for the service account. Must be unique within the organization.
    #[serde(rename = "name")]
    pub name: String,
}

impl UpdateOrgServiceAccountRequestDataAttributes {
    pub fn new(name: String) -> UpdateOrgServiceAccountRequestDataAttributes {
        UpdateOrgServiceAccountRequestDataAttributes {
            name,
        }
    }
}


