/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateGroupServiceAccountRequestData {
    #[serde(rename = "attributes")]
    pub attributes: Box<crate::models::UpdateGroupServiceAccountRequestDataAttributes>,
    /// The ID of the service account. Must match the id in the url path.
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// The Resource type.
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl UpdateGroupServiceAccountRequestData {
    pub fn new(attributes: crate::models::UpdateGroupServiceAccountRequestDataAttributes, id: uuid::Uuid, r#type: Type) -> UpdateGroupServiceAccountRequestData {
        UpdateGroupServiceAccountRequestData {
            attributes: Box::new(attributes),
            id,
            r#type,
        }
    }
}

/// The Resource type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "service_account")]
    ServiceAccount,
}

impl Default for Type {
    fn default() -> Type {
        Self::ServiceAccount
    }
}

