/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateCollectionWithProjectsRequest {
    /// IDs of items to add to a collection
    #[serde(rename = "data")]
    pub data: Vec<crate::models::DeleteProjectsFromCollectionRequestDataInner>,
}

impl UpdateCollectionWithProjectsRequest {
    pub fn new(data: Vec<crate::models::DeleteProjectsFromCollectionRequestDataInner>) -> UpdateCollectionWithProjectsRequest {
        UpdateCollectionWithProjectsRequest {
            data,
        }
    }
}


