/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateOrgProject200ResponseDataMeta {
    /// The date that the project was last uploaded and monitored using cli.
    #[serde(rename = "cli_monitored_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cli_monitored_at: Option<Option<String>>,
}

impl UpdateOrgProject200ResponseDataMeta {
    pub fn new() -> UpdateOrgProject200ResponseDataMeta {
        UpdateOrgProject200ResponseDataMeta {
            cli_monitored_at: None,
        }
    }
}


