/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */

/// UpdateOrg200ResponseData : org resource object



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateOrg200ResponseData {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::OrgAttributes>>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<Box<crate::models::OrgRelationships>>,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl UpdateOrg200ResponseData {
    /// org resource object
    pub fn new(id: uuid::Uuid, r#type: String) -> UpdateOrg200ResponseData {
        UpdateOrg200ResponseData {
            attributes: None,
            id,
            relationships: None,
            r#type,
        }
    }
}


