/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VersioningSchemaSemverType {
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl VersioningSchemaSemverType {
    pub fn new(r#type: Type) -> VersioningSchemaSemverType {
        VersioningSchemaSemverType {
            r#type,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "semver")]
    Semver,
}

impl Default for Type {
    fn default() -> Type {
        Self::Semver
    }
}

