/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */

/// VersioningSchemaSingleSelectionType : The Single Selection Versioning Schema allows manual setting of which image should be given as a recommendation.  Only one image can be set as the current recommendation. If no images are set as the current selection,  no recommendation will be given.  It is recommended to use this versioning schema if your repository's tags aren't supported by the other schemas. 



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VersioningSchemaSingleSelectionType {
    /// Whether this image should be the recommendation. Only one image can be selected at a given time. Setting this as true will remove previous selection. 
    #[serde(rename = "is_selected")]
    pub is_selected: bool,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl VersioningSchemaSingleSelectionType {
    /// The Single Selection Versioning Schema allows manual setting of which image should be given as a recommendation.  Only one image can be set as the current recommendation. If no images are set as the current selection,  no recommendation will be given.  It is recommended to use this versioning schema if your repository's tags aren't supported by the other schemas. 
    pub fn new(is_selected: bool, r#type: Type) -> VersioningSchemaSingleSelectionType {
        VersioningSchemaSingleSelectionType {
            is_selected,
            r#type,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "single-selection")]
    SingleSelection,
}

impl Default for Type {
    fn default() -> Type {
        Self::SingleSelection
    }
}

