/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct YarnBuildArgs {
    #[serde(rename = "root_workspace")]
    pub root_workspace: String,
}

impl YarnBuildArgs {
    pub fn new(root_workspace: String) -> YarnBuildArgs {
        YarnBuildArgs {
            root_workspace,
        }
    }
}


